[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snowflake-kalshi-market-data-platform"
version = "0.1.0"
description = "Kalshi data collection"
readme = "README.md"
requires-python = ">=3.1"
license = "MIT"
authors = [
    {name = "Gabe Garrido", email = "gabriel.garrido28@gmail.com"},
]
keywords = ["snowflake", "kalshi", "dbt", "prediction markets", "data engineering", "analytics"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.32.5",
    "cryptography>=46.0.5",
    "python-dotenv>=0.9.9",
    "snowflake-connector-python>=4.3.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["kalshi*", "snow_py*"]